name: Daily XP Gain

on:
  schedule:
    - cron: "55 16 * * *" # 23:55 local time (UTC+7)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily-xp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run XP update
        run: node scripts/dailyXp.js

      - name: Commit changes
        run: |
          git config --local user.name "system"
          git config --local user.email "system@example.com"

          git add src/data/playerData.ts
          git diff --cached --quiet && exit 0
          git commit -m "Gained +${GAINED_XP} XP"
          git push
